name: Export label

on:
  label:
    types: [created, edited, deleted]
  workflow_dispatch:

permissions:
  issues: read
  contents: write
  pull-requests: write

jobs:
  export_labels:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: EndBug/export-label-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  create_pull_request:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    needs:
      - export_labels
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
      - uses: actions/download-artifact@v6
        with:
          name: Label config
      - run: cp labels.yaml .github/labels.yaml
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update labels
          delete-branch: true
          title: Update labels
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: create-pull-request/patch-export-label
          add-paths: |
            .github/labels.yaml
